// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_index: dynamic(() => import("./BlogIndex")),
  core_team_index: dynamic(() => import("./CoreTeamIndex")),
  hero: dynamic(() => import("./Hero")),
  left_image_slice: dynamic(() => import("./LeftImageSlice")),
  text_block: dynamic(() => import("./TextBlock")),
};
