// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_formula_slice: dynamic(() => import("./AboutFormulaSlice")),
  about_strategy_slice: dynamic(() => import("./AboutStrategySlice")),
  about_us_slice: dynamic(() => import("./AboutUsSlice")),
  advisor_index: dynamic(() => import("./AdvisorIndex")),
  blog_index: dynamic(() => import("./BlogIndex")),
  contact_form_section: dynamic(() => import("./ContactFormSection")),
  core_team_index: dynamic(() => import("./CoreTeamIndex")),
  hero: dynamic(() => import("./Hero")),
  investor_content_slice: dynamic(() => import("./InvestorContentSlice")),
  left_image_slice: dynamic(() => import("./LeftImageSlice")),
  text_block: dynamic(() => import("./TextBlock")),
  video_background_slice: dynamic(() => import("./VideoBackgroundSlice")),
};
